name: invoice_template_preview
description: Invoice and thermal printer template preview studio for Flutter.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.3
  pdf: ^3.11.1
  printing: ^5.13.4
  intl: ^0.20.2
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample_invoice.yaml
    - assets/sample_pos.yaml
    - assets/sample_erp.yaml
